### PR TITLE
Add qwhelan as a maintainer

### PR DESCRIPTION
**Pull request by qwhelan**
I'm the maintainer of bottleneck and would like to update the release on conda-forge (see #22), so adding myself as a recipe maintainer to help out here.

### CODE REVIEW

**Comment by jakirkham** [comment]
@conda-forge-admin, please re-render.

**Comment by qwhelan** [comment]
Thanks for re-rendering. I'd like to publish a `rc` via conda-forge ASAP, so would appreciate this being merged if there are no objections.

**Comment by ocefpaf** [comment]
Before pushing an RV release here take a look at:https://github.com/conda-forge/conda-forge-enhancement-proposals/pull/3

TL;DR we'll need a label for it.

**Comment by qwhelan** [comment]
@ocefpaf Thanks, that's what I followed. I generally copied the `pandas` approach but don't see any option to create a `dev` or `rc` branch, so I just created #24 and would appreciate any comments you have on it

**Comment by ocefpaf** [comment]
Looks good. Go for it @qwhelan!

**Pull request merged**
